name: geocode-new-addresses
on:
  push:
    branches:
      - master
jobs:
  geocode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run geocode
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Geocoded newly added addresses
          commit_author: MLH Localhost <localhost@mlh.io>
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
